language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio run -e emontx-3phase_deploy
deploy:
  provider: releases
  api_key:
    secure: q+9mQYuBTjRsB2TMEEHZ3IBiPG+wPJuX+9nOS8gRnhmZ4gIWZMk+IXRi26EjwXu3T9Keu/4bbQBpu9lq1LgocvP9tHcGUIY9k1inJHYxZJPTMo62BL2F+sTDuvCkULbdZZPPAxaW6ixkXtKKQNF759IeU7UzvTyJqm0B0Z8vU277uuskyMv2H2dPSXPJLDEpKWF0CRxZZPbEBMDoQi3E+I5nK8q1EfA024TEdaSM4ndE9RDaKQpmaOOldGGVcupj9iemsQuLrjjSsSU8tSIW09lpX6PmhkpGjr1ACViw0une+CMnBjS+6kPv+3UAGuw0+NuEt7UJMJwAIZjdP80zHUnDy+LRNPO2hVrR5FMmiWcVNMBv7drXIC7mA5v1RdqJmFyqcBAN6tJzRo951uuAK5pF6LmMaXQ9Fuw1kwohPDrjtY75g/UcqRVCaZXyoVxuJ7t1jyReFquXBfmBDWuc5deUOPvDgcUY424N+SwuWpP7JBSDRdsXe4JKvuGmvxFPJTEYjx8/kwjfCI6aNYuXpDXnJw6ep6OXZdWd5oY9hqN39OfDtrQ6HHu2wLH2QZvtSOP/nCMyDHTUPXiLSeLxnNNz7Yu1DK4StgDIZEhmqD8RwB8m2hclIdKqPgGReqaU+JQI9KwkrWKRca0/qEW+BKOIBtHdtG9NtgAbItG/P7k=
  file: ".pioenvs/emontx-3phase_deploy/firmware.hex"
  on:
    repo: openenergymonitor/emontx-3phase
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"

## Setup auto depoly .hex on release tag
# gem install travis
# cd into repo
# $ travis setup releases
# folow prompts..depoly section will be populated